/**
 * egdesk.schema.ts — committed seed schema
 *
 * COMMIT THIS FILE TO GIT.
 *
 * When someone opens this project in their EGDesk, these tables are created
 * automatically in their dev database on first server start.
 *
 * Unlike egdesk.config.ts (auto-generated, gitignored), this file is the
 * portable source of truth for your app's database structure.
 */

export const TABLES = {
  "approval_requests": {
    "name": "approval_requests",
    "displayName": "견적/단가 승인 결재 요청 대장",
    "description": "타인 건 수정/승인 요청 및 심사 승인/반려 대장",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "request_type",
      "requester_user_id",
      "owner_user_id",
      "reason",
      "status",
      "reviewed_by_user_id",
      "review_comment",
      "reviewed_at",
      "expires_at",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 21,
    "rowCount": 0
  },
  "audit_logs": {
    "name": "audit_logs",
    "displayName": "시스템 감사 로그",
    "description": "EGDesk 시스템 및 플러그인 변경 감사 로그",
    "columns": [
      "id",
      "_version",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 10,
    "rowCount": 0
  },
  "bom_approval_records": {
    "name": "bom_approval_records",
    "displayName": "BOM 승인/수정 이력",
    "description": "사용자 승인 결정 및 마스터 오버라이드",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "normalized_item_id",
      "selected_master_id",
      "decision_type",
      "decision_reason",
      "difference_notes",
      "is_override",
      "approved_by_user_id",
      "approved_at",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 20,
    "rowCount": 0
  },
  "bom_areas": {
    "name": "bom_areas",
    "displayName": "BOM 검출 영역",
    "description": "도면 내 BOM 테이블 영역 바운딩 박스",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "source_file_id",
      "drawing_no",
      "table_type",
      "bbox_json",
      "confidence_score",
      "status",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 18,
    "rowCount": 74
  },
  "cad_app_settings": {
    "name": "cad_app_settings",
    "displayName": "로컬 CAD 실행 경로",
    "description": "AutoCAD / DWG FastView / TrueView 경로",
    "columns": [
      "id",
      "_version",
      "key",
      "value",
      "updated_at",
      "tenant_id",
      "uuid",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 12,
    "rowCount": 0
  },
  "cad_objects": {
    "name": "cad_objects",
    "displayName": "CAD 객체 기하 데이터",
    "description": "도면 개별 CAD 엔티티 캐시",
    "columns": [
      "id",
      "_version",
      "parse_run_id",
      "handle",
      "entity_type",
      "layer",
      "color",
      "raw_text",
      "bounding_box_json",
      "geometry_data_json",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 19,
    "rowCount": 40002
  },
  "cad_parse_runs": {
    "name": "cad_parse_runs",
    "displayName": "CAD 파싱 실행 이력",
    "description": "CAD 엔티티 파싱 통계 및 결과",
    "columns": [
      "id",
      "_version",
      "source_file_id",
      "dxf_version",
      "total_entities",
      "entity_counts_json",
      "global_bounds_json",
      "status",
      "duration_ms",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 18,
    "rowCount": 2
  },
  "case_archives": {
    "name": "case_archives",
    "displayName": "분석 스냅샷 아카이브",
    "description": "견적 건 분석 상태 스냅샷",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "archive_version",
      "archive_name",
      "drawings_count",
      "bom_items_count",
      "snapshot_data_json",
      "created_by_user_id",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 18,
    "rowCount": 0
  },
  "companies": {
    "name": "companies",
    "displayName": "고객사/협력사 대장",
    "description": "고객사 정보 및 테넌트 식별",
    "columns": [
      "id",
      "_version",
      "company_code",
      "company_name",
      "company_type",
      "is_active",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 15,
    "rowCount": 1
  },
  "drawing_relationships": {
    "name": "drawing_relationships",
    "displayName": "도면 계층 관계",
    "description": "조립도-부조립도-단품 종속 관계",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "parent_drawing_no",
      "child_drawing_no",
      "relationship_type",
      "confidence_score",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 16,
    "rowCount": 242
  },
  "drawings": {
    "name": "drawings",
    "displayName": "도면 시트 및 표제란",
    "description": "도면 번호, 품명, 규격, 척도, 리비전",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "source_file_id",
      "drawing_index",
      "drawing_no_raw",
      "drawing_no_normalized",
      "drawing_name_raw",
      "drawing_name_normalized",
      "revision",
      "material",
      "scale",
      "drawing_type",
      "is_quote_included",
      "exclude_reason",
      "frame_bbox_json",
      "title_block_bbox_json",
      "confidence_score",
      "status",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 28,
    "rowCount": 246
  },
  "dwg_conversion_runs": {
    "name": "dwg_conversion_runs",
    "displayName": "DWG 변환 실행 이력",
    "description": "LibreDWG 변환 실행 로그",
    "columns": [
      "id",
      "_version",
      "source_file_id",
      "derived_file_id",
      "provider",
      "converter_version",
      "source_dwg_signature",
      "source_dwg_version",
      "output_dxf_version",
      "status",
      "started_at",
      "completed_at",
      "duration_ms",
      "exit_code",
      "warning_count",
      "warnings_json",
      "error_code",
      "error_message",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 27,
    "rowCount": 2
  },
  "excel_templates": {
    "name": "excel_templates",
    "displayName": "엑셀 템플릿 관리",
    "description": "공식 견적서 엑셀 양식 관리",
    "columns": [
      "id",
      "_version",
      "company_id",
      "template_name",
      "original_file_name",
      "storage_path",
      "template_type",
      "version",
      "is_active",
      "is_default",
      "created_by_user_id",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 20,
    "rowCount": 0
  },
  "final_bom_items": {
    "name": "final_bom_items",
    "displayName": "최종 확정 견적 BOM",
    "description": "사용자 승인 완료된 견적 투입 최종 BOM",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "normalized_item_id",
      "final_master_id",
      "final_master_code",
      "final_name",
      "final_spec",
      "final_material",
      "final_quantity",
      "final_unit",
      "approval_status",
      "approved_by_user_id",
      "approved_at",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 23,
    "rowCount": 0
  },
  "flattened_bom_items": {
    "name": "flattened_bom_items",
    "displayName": "다단계 집계 BOM",
    "description": "도면 계층 전개 및 수량 가중치 합산 BOM",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "item_key",
      "part_no",
      "name",
      "specification",
      "material",
      "total_quantity",
      "unit",
      "source_drawings_json",
      "source_item_ids_json",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 21,
    "rowCount": 250
  },
  "golden_cases": {
    "name": "golden_cases",
    "displayName": "골든 데이터셋 케이스",
    "description": "벤치마크 및 회귀 테스트용 기준 데이터셋",
    "columns": [
      "id",
      "_version",
      "project_id",
      "quotation_case_id",
      "case_code",
      "name",
      "description",
      "data_classification",
      "source_checksum",
      "status",
      "actual_drawing_count",
      "actual_bom_count",
      "actual_item_count",
      "created_by",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 23,
    "rowCount": 0
  },
  "manual_price_pool": {
    "name": "manual_price_pool",
    "displayName": "수기 단가 지식 풀",
    "description": "미등록 품목 수기 입력 단가 축적 DB",
    "columns": [
      "id",
      "_version",
      "item_name",
      "specification",
      "material",
      "unit_price",
      "remark",
      "quotation_case_id",
      "company_id",
      "standard_name",
      "standard_material",
      "approval_count",
      "last_used_at",
      "source",
      "created_by_user_id",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 24,
    "rowCount": 0
  },
  "master_aliases": {
    "name": "master_aliases",
    "displayName": "마스터 품목 별칭 대장",
    "description": "고객사별 도면 표기 이명/약칭 매핑 학습 DB",
    "columns": [
      "id",
      "_version",
      "company_id",
      "master_id",
      "alias_name",
      "alias_normalized",
      "approval_count",
      "rejection_count",
      "scope",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 18,
    "rowCount": 0
  },
  "master_candidates": {
    "name": "master_candidates",
    "displayName": "마스터 추천 매칭 후보",
    "description": "BOM 품목별 추천 마스터 및 유사도 점수/근거",
    "columns": [
      "id",
      "_version",
      "normalized_item_id",
      "master_id",
      "master_code",
      "standard_name",
      "specification",
      "material",
      "rank",
      "total_score",
      "positive_evidence_json",
      "negative_evidence_json",
      "candidate_status",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 22,
    "rowCount": 0
  },
  "material_rates": {
    "name": "material_rates",
    "displayName": "원자재 기준 시세표",
    "description": "주조재/가공재 월별 kg당 기준 시세",
    "columns": [
      "id",
      "_version",
      "material_code",
      "material_name",
      "category",
      "unit_price_per_kg",
      "density",
      "effective_date",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 17,
    "rowCount": 0
  },
  "normalized_bom_items": {
    "name": "normalized_bom_items",
    "displayName": "정규화 BOM 아이템",
    "description": "오탈자 교정, 방향 분리, 표준 명칭 후보 매핑",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "raw_item_id",
      "raw_name",
      "normalized_name",
      "search_name",
      "direction",
      "spec_candidate",
      "material_candidate",
      "quantity",
      "unit",
      "is_quote_included",
      "exclude_reason",
      "status",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 24,
    "rowCount": 0
  },
  "order_results": {
    "name": "order_results",
    "displayName": "견적 수주/실주 결과 대장",
    "description": "견적건별 수주/실주 상태, 수주금액, 실주사유 및 학습 피드백",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "case_no",
      "quote_id",
      "order_status",
      "order_amount",
      "lost_reason_category",
      "lost_reason_detail",
      "feedback_notes",
      "registered_by",
      "registered_at",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 21,
    "rowCount": 0
  },
  "part_cost_breakdowns": {
    "name": "part_cost_breakdowns",
    "displayName": "부품별 제조원가 세부내역",
    "description": "재료비, 절단비, 절곡비, 가공비, 후처리비 산출 근거",
    "columns": [
      "id",
      "_version",
      "feature_id",
      "quotation_case_id",
      "material_cost",
      "laser_cutting_cost",
      "bending_cost",
      "tapping_cost",
      "machining_cost",
      "surface_finish_cost",
      "subtotal_cost",
      "markup_rate",
      "final_unit_price",
      "calc_formula_json",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 23,
    "rowCount": 0
  },
  "part_fabrication_features": {
    "name": "part_fabrication_features",
    "displayName": "부품별 가공 피처 대장",
    "description": "도면에서 추출된 외곽치수, 절단길이, 절곡수, 탭수, 이론중량",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "drawing_id",
      "bom_item_id",
      "process_type",
      "material_code",
      "material_density",
      "bbox_width",
      "bbox_length",
      "bbox_thickness",
      "cutting_length_total",
      "pierce_count",
      "bending_count",
      "through_hole_count",
      "tap_hole_count",
      "part_weight_kg",
      "surface_area_cm2",
      "heat_treatment",
      "surface_treatment",
      "raw_features_json",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 30,
    "rowCount": 0
  },
  "part_masters_v2": {
    "name": "part_masters_v2",
    "displayName": "v2.0 부품 식별 마스터",
    "description": "고객사+도번+Rev 결합 식별키 및 부품유형 관리",
    "columns": [
      "id",
      "_version",
      "part_key",
      "part_group_key",
      "company_id",
      "drawing_no",
      "revision",
      "part_name",
      "part_type",
      "standard_material",
      "specification",
      "last_unit_price",
      "last_quoted_at",
      "usage_count",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 23,
    "rowCount": 0
  },
  "price_history_v2": {
    "name": "price_history_v2",
    "displayName": "v2.0 수량구간별 단가 이력",
    "description": "수량 구간, 시세 기준일, 산출 근거 스냅샷 및 수주 여부 보관",
    "columns": [
      "id",
      "_version",
      "part_master_id",
      "part_key",
      "quotation_case_id",
      "quote_item_id",
      "qty_tier",
      "lot_quantity",
      "material_cost",
      "process_cost",
      "subtotal_cost",
      "margin_rate",
      "unit_price",
      "material_base_date",
      "price_basis_type",
      "basis_calc_json",
      "is_ordered",
      "confirmed_by",
      "effective_from",
      "effective_to",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 29,
    "rowCount": 0
  },
  "price_masters": {
    "name": "price_masters",
    "displayName": "기준 단가 마스터",
    "description": "마스터 품목별 표준/고객사 단가 및 유효기간",
    "columns": [
      "id",
      "_version",
      "master_id",
      "company_id",
      "price_type",
      "unit_price",
      "currency",
      "effective_from",
      "effective_to",
      "is_active",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 19,
    "rowCount": 0
  },
  "process_rates": {
    "name": "process_rates",
    "displayName": "가공/공정 단가표",
    "description": "주조공정 및 기계가공(CNC선반/밀링) 시간/중량당 단가",
    "columns": [
      "id",
      "_version",
      "process_code",
      "process_name",
      "unit_type",
      "rate_amount",
      "effective_date",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 16,
    "rowCount": 0
  },
  "product_masters": {
    "name": "product_masters",
    "displayName": "표준 마스터 품목 대장",
    "description": "자사 표준 부품/자재 품목 마스터",
    "columns": [
      "id",
      "_version",
      "company_id",
      "master_code",
      "standard_name",
      "category",
      "specification",
      "material",
      "unit",
      "status",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 19,
    "rowCount": 0
  },
  "projects": {
    "name": "projects",
    "displayName": "프로젝트 관리",
    "description": "고객사별 프로젝트 마스터",
    "columns": [
      "id",
      "_version",
      "company_id",
      "project_code",
      "project_name",
      "description",
      "status",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 16,
    "rowCount": 5
  },
  "quotation_cases": {
    "name": "quotation_cases",
    "displayName": "견적의뢰 건 관리",
    "description": "견적의뢰 번호, 상태, 진행 단계",
    "columns": [
      "id",
      "_version",
      "case_no",
      "company_id",
      "project_id",
      "case_name",
      "request_date",
      "status",
      "revision",
      "quote_readiness",
      "created_by_user_id",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by",
      "lifecycle_status",
      "trashed_at",
      "trashed_by_user_id",
      "archived_at",
      "archive_reason",
      "visibility"
    ],
    "columnCount": 26,
    "rowCount": 2
  },
  "quote_exports": {
    "name": "quote_exports",
    "displayName": "견적서 엑셀 발행 이력",
    "description": "견적서 엑셀 다운로드/발행 로그",
    "columns": [
      "id",
      "_version",
      "quote_id",
      "quote_version",
      "template_id",
      "file_name",
      "storage_path",
      "file_size",
      "export_status",
      "is_draft",
      "exported_by_user_id",
      "exported_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 20,
    "rowCount": 0
  },
  "quote_items": {
    "name": "quote_items",
    "displayName": "견적서 명세 품목",
    "description": "견적서 포함 품목 및 적용 단가/공급가",
    "columns": [
      "id",
      "_version",
      "quote_id",
      "final_bom_item_id",
      "master_id",
      "item_no",
      "master_code",
      "item_name",
      "specification",
      "material",
      "quantity",
      "unit",
      "unit_price",
      "amount",
      "price_source",
      "price_status",
      "drawing_no",
      "remark",
      "is_included",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 28,
    "rowCount": 0
  },
  "quotes": {
    "name": "quotes",
    "displayName": "견적서 마스터",
    "description": "견적서 버전, 공급가액, 할인율, 최종금액",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "quote_no",
      "quote_version",
      "company_id",
      "project_id",
      "status",
      "currency",
      "subtotal",
      "discount_type",
      "discount_rate",
      "discount_amount",
      "tax_rate",
      "tax_amount",
      "total_amount",
      "quote_date",
      "is_locked",
      "created_by_user_id",
      "approved_by_user_id",
      "approved_at",
      "override_reason",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 31,
    "rowCount": 0
  },
  "raw_bom_items": {
    "name": "raw_bom_items",
    "displayName": "CAD 추출 Raw BOM",
    "description": "표/텍스트에서 추출한 최초 BOM 원시 행",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "source_file_id",
      "drawing_no",
      "row_index",
      "item_no_raw",
      "part_no_raw",
      "name_raw",
      "specification_raw",
      "material_raw",
      "quantity_raw",
      "quantity_numeric",
      "unit_raw",
      "remark_raw",
      "source_handles_json",
      "status",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 26,
    "rowCount": 1244
  },
  "system_approval_settings": {
    "name": "system_approval_settings",
    "displayName": "전사 결재 정책 설정",
    "description": "타인 견적 수정/승인 및 관리자 최종결재 통제",
    "columns": [
      "id",
      "_version",
      "cross_user_edit_policy",
      "cross_user_approve_policy",
      "require_admin_final_quote_approval",
      "approval_valid_hours",
      "is_approval_suspended",
      "updated_by_user_id",
      "updated_at",
      "tenant_id",
      "uuid",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 16,
    "rowCount": 1
  },
  "system_baselines": {
    "name": "system_baselines",
    "displayName": "골든 기준선 벤치마크",
    "description": "골든 데이터셋 파싱 기준선 정밀도 지표",
    "columns": [
      "id",
      "_version",
      "golden_case_id",
      "baseline_name",
      "parser_version",
      "metrics_json",
      "created_by",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 16,
    "rowCount": 0
  },
  "system_settings": {
    "name": "system_settings",
    "displayName": "시스템 테넌트 설정 대장",
    "description": "테넌트별 전사 환경설정 및 정책 키-값 보관",
    "columns": [
      "id",
      "_version",
      "key",
      "value",
      "tenant_id",
      "description",
      "updated_at",
      "updated_by",
      "uuid",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 13,
    "rowCount": 1
  },
  "uploaded_files": {
    "name": "uploaded_files",
    "displayName": "업로드/파생 파일 관리",
    "description": "DWG/DXF/PDF 원본 및 변환 파일 경로/메타데이터",
    "columns": [
      "id",
      "_version",
      "quotation_case_id",
      "original_file_name",
      "stored_file_name",
      "storage_path",
      "file_type",
      "file_role",
      "derived_from_file_id",
      "file_size",
      "checksum",
      "upload_status",
      "uploaded_by_user_id",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 22,
    "rowCount": 6
  },
  "user_activity_logs": {
    "name": "user_activity_logs",
    "displayName": "사용자 감사 활동 로그",
    "description": "작업자별 로그인/견적수정/승인/파일업로드 이력",
    "columns": [
      "id",
      "_version",
      "user_id",
      "user_name",
      "user_login_id",
      "user_role",
      "activity_type",
      "quotation_case_id",
      "case_name",
      "details",
      "ip_address",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 20,
    "rowCount": 49
  },
  "user_approval_permissions": {
    "name": "user_approval_permissions",
    "displayName": "사용자별 결재/수정 세부 권한",
    "description": "작업자별 단가 수정, 견적 승인, 타인 건 수정 권한",
    "columns": [
      "id",
      "_version",
      "user_id",
      "can_edit_own",
      "can_approve_own",
      "can_edit_others",
      "can_approve_others",
      "can_edit_price",
      "can_approve_quote",
      "updated_at",
      "tenant_id",
      "uuid",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 17,
    "rowCount": 1
  },
  "user_company_access": {
    "name": "user_company_access",
    "displayName": "사용자-회사 접근 권한",
    "description": "사용자별 소속/접근 허용 고객사 매핑",
    "columns": [
      "id",
      "_version",
      "user_id",
      "company_id",
      "access_role",
      "is_active",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 14,
    "rowCount": 4
  },
  "users": {
    "name": "users",
    "displayName": "사용자 계정 대장",
    "description": "로그인 계정 및 역할 관리",
    "columns": [
      "id",
      "_version",
      "login_id",
      "password_hash",
      "name",
      "role",
      "company_id",
      "employee_number",
      "phone",
      "is_active",
      "last_login_at",
      "created_at",
      "tenant_id",
      "uuid",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "restored_at",
      "restored_by"
    ],
    "columnCount": 20,
    "rowCount": 5
  }
} as const;

export type TableName = keyof typeof TABLES;
export const TABLE_NAMES = Object.keys(TABLES) as TableName[];
