import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * EGDesk Database Proxy Middleware
 *
 * Intercepts __user_data_proxy, __browser_recording_proxy, __internal_knowledge_proxy, __company_research_proxy, __kakao_proxy, __drive_proxy, __sheets_proxy, __docs_proxy, __slides_proxy, __egdesk_http_proxy, __gmail_proxy, __apps_script_proxy, __visitor_auth_proxy, and __visitor_google_proxy requests
 * and forwards them to the EGDesk MCP HTTP server.
 * This allows CORS-free database access in both local and tunneled environments.
 *
 * Generated by @egdesk/next-api-plugin
 */

/** Forward this site's origin so EGDesk can bind visitor sessions to this site only. */
function visitorUpstreamHeaders(request: NextRequest): Record<string, string> {
  const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
  const origin = request.headers.get('origin') || request.nextUrl.origin;
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    Origin: origin,
    'X-Visitor-Origin': origin,
  };
  if (apiKey) headers['X-Api-Key'] = apiKey;
  return headers;
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Intercept __user_data_proxy requests
  if (pathname.includes('__user_data_proxy')) {
    try {
      const body = await request.text();

      // Read API key and URL from environment
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      // Forward to EGDesk MCP server
      const response = await fetch(`${apiUrl}/user-data/tools/call`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__browser_recording_proxy')) {
    try {
      const body = await request.text();

      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      const response = await fetch(`${apiUrl}/browser-recording/tools/call`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__internal_knowledge_proxy')) {
    try {
      const body = await request.text();

      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      const response = await fetch(`${apiUrl}/internal-knowledge/tools/call`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__company_research_proxy')) {
    try {
      const body = await request.text();

      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      const response = await fetch(`${apiUrl}/company-research/tools/call`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__kakao_proxy')) {
    try {
      const body = await request.text();

      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      const response = await fetch(`${apiUrl}/kakao/tools/call`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__drive_proxy')) {
    try {
      const body = await request.text();
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-Api-Key'] = apiKey;

      const response = await fetch(`${apiUrl}/drive/tools/call`, {
        method: 'POST',
        headers,
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__docs_proxy')) {
    try {
      const body = await request.text();
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-Api-Key'] = apiKey;

      const response = await fetch(`${apiUrl}/docs/tools/call`, {
        method: 'POST',
        headers,
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__slides_proxy')) {
    try {
      const body = await request.text();
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-Api-Key'] = apiKey;

      const response = await fetch(`${apiUrl}/slides/tools/call`, {
        method: 'POST',
        headers,
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__sheets_proxy')) {
    try {
      const body = await request.text();
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-Api-Key'] = apiKey;

      const response = await fetch(`${apiUrl}/sheets/tools/call`, {
        method: 'POST',
        headers,
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__egdesk_http_proxy')) {
    try {
      const payload = await request.json().catch(() => ({} as Record<string, unknown>));
      const allowed = new Set(['/sheets/sync', '/drive/sync', '/apps-script/sync']);
      const targetPath = typeof payload.path === 'string' ? payload.path.split('?')[0] : '';
      if (!allowed.has(targetPath)) {
        return NextResponse.json({ error: 'Path not allowed', path: targetPath }, { status: 400 });
      }
      const method = payload.method === 'POST' ? 'POST' : 'GET';
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const projectId = process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID;
      const egdeskEnv = process.env.NEXT_PUBLIC_EGDESK_ENV;
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-Api-Key'] = apiKey;
      if (projectId) headers['X-EGDesk-Project-Id'] = projectId;
      if (egdeskEnv) headers['X-EGDesk-Env'] = egdeskEnv;
      const base = apiUrl.endsWith('/') ? apiUrl : `${apiUrl}/`;
      const url = new URL(targetPath.startsWith('/') ? targetPath.slice(1) : targetPath, base);
      const query = payload.query && typeof payload.query === 'object' ? payload.query as Record<string, unknown> : {};
      for (const [key, value] of Object.entries(query)) {
        if (typeof value === 'string' && value) url.searchParams.set(key, value);
      }
      const response = await fetch(url.toString(), {
        method,
        headers,
        body: method === 'POST' ? JSON.stringify(payload.body || {}) : undefined,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__gmail_proxy')) {
    try {
      const body = await request.text();
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-Api-Key'] = apiKey;
      const response = await fetch(`${apiUrl}/gmail/tools/call`, {
        method: 'POST',
        headers,
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__apps_script_proxy')) {
    try {
      const body = await request.text();
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-Api-Key'] = apiKey;
      const response = await fetch(`${apiUrl}/apps-script/tools/call`, {
        method: 'POST',
        headers,
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__visitor_auth_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/visitor-auth/tools/call`, {
        method: 'POST',
        headers: visitorUpstreamHeaders(request),
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__visitor_google_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers = visitorUpstreamHeaders(request);
      const authorization = request.headers.get('authorization');
      if (authorization) headers['Authorization'] = authorization;

      const response = await fetch(`${apiUrl}/visitor-google/tools/call`, {
        method: 'POST',
        headers,
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  // Continue to next middleware or route
  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
};
